# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/speedtest-go-exporter

kos:
  - repositories: [ghcr.io/zakame/speedtest-go-exporter]
    tags: ["{{.Version}}"]
    bare: true
    preserve_import_paths: false
    sbom: spdx
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.openconatiners.image.created": "{{.Date}}"
      "org.openconatiners.image.title": "{{.ProjectName}}"
      "org.openconatiners.image.revision": "{{.FullCommit}}"
      "org.openconatiners.image.version": "{{.Version}}"
      "org.openconatiners.image.authors": "Zak B. Elep https://github.com/zakame"
      "org.openconatiners.image.source": "https://github.com/zakame/speedtest-go-exporter"
      "org.openconatiners.image.url": "https://github.com/zakame/speedtest-go-exporter/pkgs/container/speedtest-go-exporter"
      "org.openconatiners.image.description": "speedtest-go exporter"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
