apiVersion: v1
kind: Service
metadata:
  name: speedtest-go-exporter
  labels:
    app.kubernetes.io/name: speedtest-go-exporter
spec:
  selector:
    app.kubernetes.io/name: speedtest-go-exporter
  ports:
  - name: http
    port: 9798
    targetPort: http
    protocol: TCP
