name: CI

on: pull_request

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
      with:
        version: v2.11.3

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - # gotestsum v.13.0
      run: >-
        go run gotest.tools/gotestsum@c4a0df2e75a225d979a444342dd3db752b53619f
        --jsonfile unit-tests.json
        --format testdox
        --
        -v -cover -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic
        -timeout 20m ./...
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results
        path: unit-tests.json
      if: ${{ !cancelled() }}
