name: Report

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
      with:
        artifact: test-results
        name: go test
        path: unit-tests.json
        reporter: golang-json
